apiVersion: v1
kind: Service
metadata:
  name: database-service
  namespace: backend
spec:
  type: ExternalName
  externalName: databaseawseks.cj6eaisggknw.us-west-2.rds.amazonaws.com
  ports:
    - protocol: TCP
      port: 3306
