
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: nginx
          ports:
            - containerPort: 80
          env:
            - name: DB_HOST
              value: "rds-service"
            - name: DB_PORT
              value: "3306"  # Replace with your RDS port if different
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: password

---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: demo
spec:
  selector:
    app: backend
    type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

      
 
