apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
spec:
  selector:
    matchLabels:
      app: myapp
  replicas: 2
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: 533266970869.dkr.ecr.us-east-1.amazonaws.com/awseksshiv:latest
        ports:
        - containerPort: 80
